// <auto-generated />
using System;
using AuthApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231028201116_AddBooks")]
    partial class AddBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthApp.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AuthApp.Data.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Author = "Emmalee West",
                            Isbn = "cytinbfvyg",
                            Title = "functionalities",
                            Year = 1991
                        },
                        new
                        {
                            Id = 2L,
                            Author = "Araceli Bode",
                            Isbn = "4slj4n7vae",
                            Title = "Naira",
                            Year = 2010
                        },
                        new
                        {
                            Id = 3L,
                            Author = "Josh Walsh",
                            Isbn = "j87comuj5x",
                            Title = "connect",
                            Year = 1963
                        },
                        new
                        {
                            Id = 4L,
                            Author = "Pat Prohaska",
                            Isbn = "brvfvasc6b",
                            Title = "Chad",
                            Year = 1915
                        },
                        new
                        {
                            Id = 5L,
                            Author = "Keira Waelchi",
                            Isbn = "c0xih8ega8",
                            Title = "Sleek Wooden Fish",
                            Year = 1954
                        },
                        new
                        {
                            Id = 6L,
                            Author = "Brian Baumbach",
                            Isbn = "3k24v2mnqw",
                            Title = "Home Loan Account",
                            Year = 1902
                        },
                        new
                        {
                            Id = 7L,
                            Author = "Henri Jacobi",
                            Isbn = "cl55u7ujhz",
                            Title = "Awesome Rubber Gloves",
                            Year = 1974
                        },
                        new
                        {
                            Id = 8L,
                            Author = "Chad Bode",
                            Isbn = "yx1movpd7m",
                            Title = "Fantastic Metal Soap",
                            Year = 1956
                        },
                        new
                        {
                            Id = 9L,
                            Author = "Skylar Wintheiser",
                            Isbn = "s190zw8d8k",
                            Title = "fuchsia",
                            Year = 1948
                        },
                        new
                        {
                            Id = 10L,
                            Author = "Laverna Hettinger",
                            Isbn = "5fvglddroq",
                            Title = "Small",
                            Year = 1953
                        },
                        new
                        {
                            Id = 11L,
                            Author = "Kraig Howe",
                            Isbn = "cm3m8bgk66",
                            Title = "calculate",
                            Year = 1989
                        },
                        new
                        {
                            Id = 12L,
                            Author = "Ambrose Gulgowski",
                            Isbn = "sorug0beal",
                            Title = "South Dakota",
                            Year = 1953
                        },
                        new
                        {
                            Id = 13L,
                            Author = "Duane Lockman",
                            Isbn = "4ltu8szec1",
                            Title = "methodical",
                            Year = 1987
                        },
                        new
                        {
                            Id = 14L,
                            Author = "Dorris Stracke",
                            Isbn = "tjpdyqzs4d",
                            Title = "SMTP",
                            Year = 1903
                        },
                        new
                        {
                            Id = 15L,
                            Author = "Amanda Schroeder",
                            Isbn = "1uan24qzti",
                            Title = "indigo",
                            Year = 1998
                        },
                        new
                        {
                            Id = 16L,
                            Author = "Pierce Roberts",
                            Isbn = "5n4frvk8bs",
                            Title = "hardware",
                            Year = 1915
                        },
                        new
                        {
                            Id = 17L,
                            Author = "Jayda Doyle",
                            Isbn = "k7cj0uk17q",
                            Title = "wireless",
                            Year = 1909
                        },
                        new
                        {
                            Id = 18L,
                            Author = "Rowland Corwin",
                            Isbn = "fkzd7d2cax",
                            Title = "Turnpike",
                            Year = 1958
                        },
                        new
                        {
                            Id = 19L,
                            Author = "Roma Welch",
                            Isbn = "b2hmylyvsw",
                            Title = "Personal Loan Account",
                            Year = 1972
                        },
                        new
                        {
                            Id = 20L,
                            Author = "Maynard Pollich",
                            Isbn = "and6djta9t",
                            Title = "Personal Loan Account",
                            Year = 1959
                        },
                        new
                        {
                            Id = 21L,
                            Author = "Leonie Lind",
                            Isbn = "8l69e03awj",
                            Title = "backing up",
                            Year = 1958
                        },
                        new
                        {
                            Id = 22L,
                            Author = "Jerrod Mraz",
                            Isbn = "r5nlmt8she",
                            Title = "Danish Krone",
                            Year = 1962
                        },
                        new
                        {
                            Id = 23L,
                            Author = "Paula Koelpin",
                            Isbn = "qw98nzfnao",
                            Title = "override",
                            Year = 1926
                        },
                        new
                        {
                            Id = 24L,
                            Author = "Lizeth Torp",
                            Isbn = "ulsn2b7gzp",
                            Title = "grow",
                            Year = 2021
                        },
                        new
                        {
                            Id = 25L,
                            Author = "Sasha Turcotte",
                            Isbn = "8vhfskfyum",
                            Title = "wireless",
                            Year = 1942
                        },
                        new
                        {
                            Id = 26L,
                            Author = "Sylvia Johnson",
                            Isbn = "fr5ljwzkq4",
                            Title = "Guatemala",
                            Year = 1966
                        },
                        new
                        {
                            Id = 27L,
                            Author = "Jude Pacocha",
                            Isbn = "5psdgcv1tb",
                            Title = "Glens",
                            Year = 1953
                        },
                        new
                        {
                            Id = 28L,
                            Author = "Agustin Rath",
                            Isbn = "tukka8n4bz",
                            Title = "Personal Loan Account",
                            Year = 1929
                        },
                        new
                        {
                            Id = 29L,
                            Author = "Elody Gerhold",
                            Isbn = "54f5gmqyg2",
                            Title = "pricing structure",
                            Year = 1967
                        },
                        new
                        {
                            Id = 30L,
                            Author = "Earnestine Brakus",
                            Isbn = "a1j0bpvq8g",
                            Title = "array",
                            Year = 1962
                        },
                        new
                        {
                            Id = 31L,
                            Author = "Grady Emmerich",
                            Isbn = "14qk6b6sj2",
                            Title = "Locks",
                            Year = 1910
                        },
                        new
                        {
                            Id = 32L,
                            Author = "Jennings Reynolds",
                            Isbn = "hbu8p7rqzk",
                            Title = "RAM",
                            Year = 1932
                        },
                        new
                        {
                            Id = 33L,
                            Author = "Meredith Willms",
                            Isbn = "2ak81f0r4s",
                            Title = "eyeballs",
                            Year = 1910
                        },
                        new
                        {
                            Id = 34L,
                            Author = "Ursula Ferry",
                            Isbn = "tr8iy6q7o0",
                            Title = "Adaptive",
                            Year = 1935
                        },
                        new
                        {
                            Id = 35L,
                            Author = "Adalberto Turner",
                            Isbn = "wz3l0sbvgb",
                            Title = "deliverables",
                            Year = 1960
                        },
                        new
                        {
                            Id = 36L,
                            Author = "Holly Mraz",
                            Isbn = "zqsqqh5orr",
                            Title = "Oregon",
                            Year = 1938
                        },
                        new
                        {
                            Id = 37L,
                            Author = "Albina Gerlach",
                            Isbn = "r7w35exfiw",
                            Title = "Unbranded Concrete Fish",
                            Year = 1995
                        },
                        new
                        {
                            Id = 38L,
                            Author = "Lindsey Anderson",
                            Isbn = "s20jmz9fqa",
                            Title = "turquoise",
                            Year = 1940
                        },
                        new
                        {
                            Id = 39L,
                            Author = "Nasir Kassulke",
                            Isbn = "mqa8sijitb",
                            Title = "wireless",
                            Year = 2004
                        },
                        new
                        {
                            Id = 40L,
                            Author = "Kolby Hudson",
                            Isbn = "ha5a9t76e9",
                            Title = "core",
                            Year = 1961
                        },
                        new
                        {
                            Id = 41L,
                            Author = "Queenie Schumm",
                            Isbn = "l8o391w8th",
                            Title = "back-end",
                            Year = 1930
                        },
                        new
                        {
                            Id = 42L,
                            Author = "Cortney Rowe",
                            Isbn = "o0ucs1negl",
                            Title = "Georgia",
                            Year = 1953
                        },
                        new
                        {
                            Id = 43L,
                            Author = "Wallace Haag",
                            Isbn = "pdp0qmm5bc",
                            Title = "Taiwan",
                            Year = 1971
                        },
                        new
                        {
                            Id = 44L,
                            Author = "Dorian Adams",
                            Isbn = "znkgys0ryt",
                            Title = "Incredible Soft Chair",
                            Year = 1927
                        },
                        new
                        {
                            Id = 45L,
                            Author = "Jordon Batz",
                            Isbn = "9irut6h42v",
                            Title = "Cambridgeshire",
                            Year = 1965
                        },
                        new
                        {
                            Id = 46L,
                            Author = "Eric McLaughlin",
                            Isbn = "fbfj7eurlp",
                            Title = "Industrial",
                            Year = 1929
                        },
                        new
                        {
                            Id = 47L,
                            Author = "Green Pacocha",
                            Isbn = "gtjst16gth",
                            Title = "transmit",
                            Year = 1963
                        },
                        new
                        {
                            Id = 48L,
                            Author = "Henderson Schimmel",
                            Isbn = "ssm8s5eytv",
                            Title = "Montserrat",
                            Year = 1984
                        },
                        new
                        {
                            Id = 49L,
                            Author = "Ulises Ratke",
                            Isbn = "cn726o6ik9",
                            Title = "Music",
                            Year = 2008
                        },
                        new
                        {
                            Id = 50L,
                            Author = "May Swift",
                            Isbn = "8csxf5jmi1",
                            Title = "Causeway",
                            Year = 2006
                        },
                        new
                        {
                            Id = 51L,
                            Author = "Brannon Bailey",
                            Isbn = "wbvs6uecm4",
                            Title = "capacitor",
                            Year = 1976
                        },
                        new
                        {
                            Id = 52L,
                            Author = "Johnpaul Gerlach",
                            Isbn = "tw4zgnh6ik",
                            Title = "Metal",
                            Year = 1998
                        },
                        new
                        {
                            Id = 53L,
                            Author = "Tyrese Fisher",
                            Isbn = "djdjq9j0uz",
                            Title = "Handcrafted Steel Gloves",
                            Year = 1921
                        },
                        new
                        {
                            Id = 54L,
                            Author = "Alexandro Stracke",
                            Isbn = "398ylxoce5",
                            Title = "neural",
                            Year = 1945
                        },
                        new
                        {
                            Id = 55L,
                            Author = "Ramona Reinger",
                            Isbn = "ca6dq54p3m",
                            Title = "Implemented",
                            Year = 1972
                        },
                        new
                        {
                            Id = 56L,
                            Author = "Marianne Hackett",
                            Isbn = "dpjxxesdca",
                            Title = "Orchestrator",
                            Year = 1986
                        },
                        new
                        {
                            Id = 57L,
                            Author = "Anastasia Crooks",
                            Isbn = "73nvmfapyk",
                            Title = "Tasty Cotton Pants",
                            Year = 1918
                        },
                        new
                        {
                            Id = 58L,
                            Author = "Violette Bernhard",
                            Isbn = "o3roofvbkx",
                            Title = "access",
                            Year = 2002
                        },
                        new
                        {
                            Id = 59L,
                            Author = "Wilbert Dach",
                            Isbn = "aqkfri1fr9",
                            Title = "Small",
                            Year = 1928
                        },
                        new
                        {
                            Id = 60L,
                            Author = "Rory Murphy",
                            Isbn = "1bcmhvnodq",
                            Title = "Virtual",
                            Year = 1941
                        },
                        new
                        {
                            Id = 61L,
                            Author = "Verda Schinner",
                            Isbn = "caqs9fql7k",
                            Title = "primary",
                            Year = 1980
                        },
                        new
                        {
                            Id = 62L,
                            Author = "Gwen Kirlin",
                            Isbn = "7whxviqdhb",
                            Title = "invoice",
                            Year = 1978
                        },
                        new
                        {
                            Id = 63L,
                            Author = "Horacio Ratke",
                            Isbn = "xgywyh6k7a",
                            Title = "Clothing",
                            Year = 1990
                        },
                        new
                        {
                            Id = 64L,
                            Author = "Roderick Dibbert",
                            Isbn = "naxifb52al",
                            Title = "Steel",
                            Year = 2010
                        },
                        new
                        {
                            Id = 65L,
                            Author = "Litzy Hudson",
                            Isbn = "jvrup71hiq",
                            Title = "Networked",
                            Year = 1989
                        },
                        new
                        {
                            Id = 66L,
                            Author = "Korbin Russel",
                            Isbn = "lbn4zr96ze",
                            Title = "International",
                            Year = 1996
                        },
                        new
                        {
                            Id = 67L,
                            Author = "Emelie Beatty",
                            Isbn = "8oytrud74z",
                            Title = "infomediaries",
                            Year = 1976
                        },
                        new
                        {
                            Id = 68L,
                            Author = "Pascale Purdy",
                            Isbn = "efhizlldnm",
                            Title = "redundant",
                            Year = 1933
                        },
                        new
                        {
                            Id = 69L,
                            Author = "Itzel Walsh",
                            Isbn = "td6gh1ywtx",
                            Title = "Syrian Pound",
                            Year = 1928
                        },
                        new
                        {
                            Id = 70L,
                            Author = "Brooklyn Hessel",
                            Isbn = "yueazcw5bg",
                            Title = "Sleek",
                            Year = 1978
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AuthApp.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AuthApp.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthApp.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AuthApp.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
